# Generated by Django 3.1.9 on 2021-09-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('rules', models.CharField(max_length=200)),
                ('judging_parameter', models.CharField(max_length=500)),
                ('registration_link', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=100)),
                ('prize1', models.IntegerField()),
                ('prize2', models.IntegerField()),
                ('prize3', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_name', to='api.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prize', to='api.prize'),
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_year', to='api.year'),
        ),
    ]
