# Generated by Django 3.1.9 on 2021-09-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210902_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='name',
            new_name='member_name',
        ),
    ]
