# Generated by Django 3.2.6 on 2021-09-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('type', models.CharField(choices=[('Coding', 'Coding'), ('Robotics', 'Robotics'), ('Departmental', 'Departmental'), ('Gaming', 'Gaming')], default='Coding', max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('total_prize', models.CharField(max_length=100)),
                ('registration_link', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
                ('meet_link', models.CharField(max_length=100)),
                ('doc_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Co-Coordinator', 'Co-Coordinator')], default='Coordinator', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('contact_no', models.CharField(max_length=50)),
                ('event_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='api.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_year', to='api.year'),
        ),
    ]
