# Generated by Django 3.2.6 on 2021-09-04 03:52

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210903_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='judging_parameter',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='rules',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='prize',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
