# Generated by Django 3.2.6 on 2021-09-12 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210911_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Coding', 'Coding'), ('Robotics', 'Robotics'), ('Departmental CSE', 'Departmental CSE'), ('Departmental ECE', 'Departmental ECE'), ('Departmental EE', 'Departmental EE'), ('Departmental ME', 'Departmental ME'), ('Departmental CE', 'Departmental CE'), ('Gaming', 'Gaming'), ('Other', 'Other')], default='Coding', max_length=200),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='event_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='api.event'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='type',
            field=models.CharField(choices=[('Coordinator', 'Coordinator'), ('Co-Coordinator', 'Co-Coordinator'), ('General Secretary-Tech', 'General Secretary-Tech'), ('Core Member', 'Core Member')], default='Coordinator', max_length=100),
        ),
    ]
