# Generated by Django 3.2.6 on 2021-09-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210904_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meet_link',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='contact_no',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
